-- RUN THIS IN YOUR SUPABASE SQL EDITOR

-- 1. Create the juices table
CREATE TABLE juices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price DECIMAL NOT NULL,
  category TEXT,
  image TEXT,
  calories INTEGER,
  size TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create the subscriptions table
CREATE TABLE subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  juice_id BIGINT REFERENCES juices(id) ON DELETE SET NULL,
  plan_id TEXT NOT NULL,
  quantity INTEGER DEFAULT 1,
  delivery_time TEXT,
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  customer_address TEXT NOT NULL,
  start_date DATE NOT NULL,
  total DECIMAL NOT NULL,
  status TEXT DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Insert initial juice data
INSERT INTO juices (name, description, price, category, image, calories, size)
VALUES 
('Green Goddess', 'Spinach, kale, apple, cucumber, lemon, ginger', 149, 'detox', '🥬', 120, '500ml'),
('Sunrise Boost', 'Orange, carrot, turmeric, ginger, lemon', 129, 'energy', '🍊', 150, '500ml'),
('Berry Shield', 'Blueberry, strawberry, acai, pomegranate, honey', 179, 'immunity', '🫐', 180, '500ml'),
('Tropical Breeze', 'Pineapple, mango, coconut water, mint', 139, 'refresh', '🍍', 140, '500ml'),
('Power Punch', 'Banana, peanut butter, oats, almond milk, honey', 199, 'protein', '💪', 320, '500ml'),
('Citrus Cleanse', 'Grapefruit, orange, lemon, lime, mint', 119, 'detox', '🍋', 95, '500ml');

-- 4. Enable Row Level Security (OPTIONAL - but recommended for production)
-- ALTER TABLE juices ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;

-- Create policies (Allowing all access for simplicity during setup)
CREATE POLICY "Allow public read juices" ON juices FOR SELECT USING (true);
CREATE POLICY "Allow public insert subscriptions" ON subscriptions FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public read own subscriptions" ON subscriptions FOR SELECT USING (true);
CREATE POLICY "Allow public update own subscriptions" ON subscriptions FOR UPDATE USING (true);
