-- RUN THIS IN YOUR SUPABASE SQL EDITOR

-- 1. Create the juices table
CREATE TABLE IF NOT EXISTS juices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price DECIMAL NOT NULL,
  category TEXT,
  image TEXT,
  calories INTEGER,
  size TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create the subscriptions table with user_id reference
CREATE TABLE IF NOT EXISTS subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  juice_id BIGINT REFERENCES juices(id) ON DELETE SET NULL,
  plan_id TEXT NOT NULL,
  quantity INTEGER DEFAULT 1,
  delivery_time TEXT,
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  customer_address TEXT NOT NULL,
  start_date DATE NOT NULL,
  total DECIMAL NOT NULL,
  status TEXT DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Insert initial juice data (if not exists)
INSERT INTO juices (name, description, price, category, image, calories, size)
SELECT * FROM (VALUES 
  ('Green Goddess', 'Spinach, kale, apple, cucumber, lemon, ginger', 149, 'detox', '🥬', 120, '500ml'),
  ('Sunrise Boost', 'Orange, carrot, turmeric, ginger, lemon', 129, 'energy', '🍊', 150, '500ml'),
  ('Berry Shield', 'Blueberry, strawberry, acai, pomegranate, honey', 179, 'immunity', '🫐', 180, '500ml'),
  ('Tropical Breeze', 'Pineapple, mango, coconut water, mint', 139, 'refresh', '🍍', 140, '500ml'),
  ('Power Punch', 'Banana, peanut butter, oats, almond milk, honey', 199, 'protein', '💪', 320, '500ml'),
  ('Citrus Cleanse', 'Grapefruit, orange, lemon, lime, mint', 119, 'detox', '🍋', 95, '500ml')
) AS v(name, description, price, category, image, calories, size)
WHERE NOT EXISTS (SELECT 1 FROM juices LIMIT 1);

-- 4. Enable Row Level Security
ALTER TABLE juices ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;

-- 5. Drop existing policies if they exist
DROP POLICY IF EXISTS "Allow public read juices" ON juices;
DROP POLICY IF EXISTS "Allow public insert subscriptions" ON subscriptions;
DROP POLICY IF EXISTS "Allow public read own subscriptions" ON subscriptions;
DROP POLICY IF EXISTS "Allow public update own subscriptions" ON subscriptions;

-- 6. Create policies for juices (public read access)
CREATE POLICY "Allow public read juices" ON juices
  FOR SELECT USING (true);

-- 7. Create policies for subscriptions (user-specific access)
CREATE POLICY "Users can view their own subscriptions" ON subscriptions
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can create their own subscriptions" ON subscriptions
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own subscriptions" ON subscriptions
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own subscriptions" ON subscriptions
  FOR DELETE USING (auth.uid() = user_id);

-- 8. Create policy for admin users to view all subscriptions
-- Admin users have role='admin' in their user_metadata
CREATE POLICY "Admins can view all subscriptions" ON subscriptions
  FOR SELECT USING (
    (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin'
  );

-- 9. Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_subscriptions_user_id ON subscriptions(user_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_status ON subscriptions(status);
CREATE INDEX IF NOT EXISTS idx_juices_category ON juices(category);
